import { expect, test } from '@playwright/test'
import { readFile } from 'node:fs/promises'
import { resolve } from 'node:path'

test('production UI creates, saves, restores and exports a workbench without test hooks', async ({ page }, testInfo) => {
  const pageErrors: string[] = []
  page.on('pageerror', (error) => pageErrors.push(error.message))
  await page.goto('/')
  await expect(page.getByTestId('template-bench')).toBeVisible()
  expect(await page.evaluate(() => '__aluframe' in window)).toBe(false)
  await expect(page.getByTestId('viewport').locator('canvas')).toBeVisible()
  await expect(page.getByTestId('bom-count')).toHaveText('0')

  await page.getByTestId('template-bench').click()
  const length = page.getByTestId('template-block').getByRole('spinbutton', { name: '长', exact: true })
  await length.fill('1200')
  await length.press('Enter')
  await page.getByTestId('template-place').click()
  await expect(page.getByTestId('bom-count')).toHaveText('12')
  const memberLength = page.getByTestId('properties').getByRole('spinbutton', { name: '中心线长度 (mm)', exact: true })
  await memberLength.fill('950')
  await memberLength.press('Enter')
  await expect(memberLength).toHaveValue('950')
  await page.getByTestId('through-posts').click()
  await expect(page.getByTestId('through-posts')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('autosave-status')).toHaveAttribute('data-state', 'saved')
  const overall = await page.getByTestId('bom-overall').textContent()
  const parts = await page.getByTestId('bom-table').textContent()
  expect(overall).toMatch(/^\d+×\d+×\d+$/)
  await page.getByTestId('fit-view').click()
  await page.getByTestId('viewport').screenshot({ path: testInfo.outputPath('production-workbench.png') })

  await page.reload()
  await expect(page.getByTestId('bom-count')).toHaveText('12')
  await expect(page.getByTestId('through-posts')).toHaveAttribute('aria-pressed', 'true')
  await expect(page.getByTestId('autosave-status')).toHaveAttribute('data-state', 'saved')
  await expect(page.getByTestId('bom-overall')).toHaveText(overall!)
  await expect(page.getByTestId('bom-table')).toHaveText(parts!)
  expect(await page.evaluate(() => '__aluframe' in window)).toBe(false)

  const downloadEvent = page.waitForEvent('download')
  await page.getByTestId('export-bom').click()
  const download = await downloadEvent
  expect(download.suggestedFilename()).toBe('BOM.csv')
  const chunks: Buffer[] = []
  for await (const chunk of (await download.createReadStream())!) chunks.push(chunk)
  const csv = Buffer.concat(chunks).toString('utf8')
  expect(csv).toContain('Category,Item,Spec,Cut length (mm),Quantity')
  const profileRows = csv.split('\n').filter((line) => line.startsWith('Profile,'))
  expect(profileRows).toHaveLength(4)
  expect(profileRows.reduce((sum, row) => sum + Number(row.split(',')[4]), 0)).toBe(12)
  expect(csv).toContain('Profile,4040,4040,950,1')
  expect(csv).toContain(`Summary,Overall WxDxH,${overall!.replaceAll('×', 'x')}`)
  expect(pageErrors).toEqual([])
})

test('production imports a repository project through the file input and restores it after reload', async ({ page }) => {
  const path = resolve('examples/flat/12-vanity.json')
  const drawing = JSON.parse(await readFile(path, 'utf8'))
  await page.goto('/')
  await expect(page.getByTestId('bom-count')).toHaveText('0')
  expect(await page.evaluate(() => '__aluframe' in window)).toBe(false)
  await page.locator('input[type="file"]').setInputFiles(path)
  await expect(page.getByTestId('toasts')).toContainText('工程已载入')
  await expect(page.getByTestId('bom-count')).toHaveText(String(drawing.profiles.length))
  await expect(page.getByTestId('bom-panels')).toBeVisible()
  await expect(page.getByTestId('save-as')).toHaveCount(0)
  await expect(page.getByTestId('autosave-status')).toHaveAttribute('data-state', 'saved')
  const parts = await page.getByTestId('bom-table').textContent()
  await page.reload()
  await expect(page.getByTestId('bom-count')).toHaveText(String(drawing.profiles.length))
  await expect(page.getByTestId('bom-table')).toHaveText(parts!)
  expect(await page.evaluate(() => '__aluframe' in window)).toBe(false)
})
