import { test, expect } from '@playwright/test'
import { openApp, store, w2c } from './helpers'

async function loadParts(page: import('@playwright/test').Page) {
  await page.evaluate(() => {
    const profile = (id: string, x: number) => ({ id, spec: '2020', length: 500, position: [x, 100, 0], quaternion: [0, 0, 0, 1], holes: [], miterCuts: [] })
    const api = (window as any).__aluframe
    api.store.getState().loadDocument({ profiles: [profile('first', 0), profile('second', 300)], connectors: [], panels: [], fittings: [], equipment: [] })
    api.tool.getState().putDown()
  })
}

test('object search, Shift selection, isolation and restore preserve document and history', async ({ page }) => {
  await openApp(page)
  await loadParts(page)
  const before = await store(page)
  await page.getByTestId('sidebar-tab-objects').click()
  const first = page.getByTestId('object-row').filter({ hasText: 'P-first' })
  const second = page.getByTestId('object-row').filter({ hasText: 'P-second' })
  await first.getByRole('button').first().click()
  await second.getByRole('button').first().click({ modifiers: ['Shift'] })
  expect((await store(page)).selectedIds).toEqual(['first', 'second'])
  await expect(page.getByTestId('sidebar-tab-objects')).toHaveAttribute('aria-selected', 'true')
  await first.getByRole('button').first().click()
  await page.getByTitle('只显示选中对象', { exact: true }).click()
  await expect(second).toHaveClass(/is-hidden/)
  const sceneIds = () => page.evaluate(() => { const ids: string[] = []; (window as any).__aluframe.sceneRoot.traverse((o: any) => { if (o.userData.profileId) ids.push(o.userData.profileId) }); return [...new Set(ids)] })
  await expect.poll(sceneIds).not.toContain('second')
  const point = await w2c(page, [300, 100, 250])
  expect(await page.evaluate(p => (window as any).__aluframe.pickAt(p.x, p.y).some((h: any) => h.id === 'second'), point)).toBe(false)
  await page.getByTitle('恢复全部可见', { exact: true }).click()
  await expect.poll(sceneIds).toContain('second')
  await page.getByTestId('object-search').fill('2020')
  await expect(page.getByTestId('object-row')).toHaveCount(2)
  await page.getByTestId('object-search').fill('P-second')
  await expect(page.getByTestId('object-row')).toHaveCount(1)
  const after = await store(page)
  expect(after.profiles).toEqual(before.profiles)
  expect(after.past).toBe(before.past)
})

test('task tabs stay fixed and creation forms open only on request', async ({ page }) => {
  await openApp(page)
  await expect(page.getByTestId('drawer-height')).not.toBeVisible()
  await page.getByTestId('configure-drawer').click()
  await expect(page.getByTestId('drawer-height')).toBeVisible()
  await expect(page.getByTestId('hinge-left')).not.toBeVisible()
  await page.getByTestId('configure-door').click()
  await expect(page.getByTestId('drawer-height')).not.toBeVisible()
  await expect(page.getByTestId('hinge-left')).toBeVisible()
  await page.getByTestId('sidebar-tab-properties').click()
  await expect(page.getByTestId('section-properties')).toBeVisible()
  await expect(page.getByTestId('fitting-block')).not.toBeVisible()
  await expect(page.getByTestId('sidebar-tab-add')).toBeInViewport()
})

test('selection candidates respect assembly visibility and object selection reveals the part', async ({ page }) => {
  await openApp(page)
  await loadParts(page)
  await page.evaluate(() => {
    const tool = (window as any).__aluframe.tool.getState()
    tool.setBuildStep(0)
    tool.setFrameSelectRect({x1: 0, y1: 0, x2: 2000, y2: 2000})
  })
  await expect.poll(async () => (await store(page)).selectedIds.length).toBeLessThan(2)
  await page.getByTestId('sidebar-tab-objects').click()
  await page.evaluate(() => (window as any).__aluframe.tool.getState().setSection({ axis: 'x', at: 9000, flip: false }))
  await page.getByTestId('object-row').filter({ hasText: 'P-second' }).getByRole('button').first().click()
  expect(await page.evaluate(() => {
    const tool = (window as any).__aluframe.tool.getState()
    return {step: tool.buildStep, section: tool.section}
  })).toEqual({step:null, section:null})
  expect((await store(page)).selectedIds).toEqual(['second'])
})

test('persistent groups select all members, survive undo and copy with fresh IDs', async ({ page }) => {
  await openApp(page)
  await loadParts(page)
  await page.getByTestId('sidebar-tab-objects').click()
  await page.getByTestId('object-row').first().getByRole('button').first().click()
  await page.getByTestId('object-row').nth(1).getByRole('button').first().click({ modifiers: ['Shift'] })
  await page.getByTestId('group-create').click()
  await page.getByRole('textbox', { name: '组名称', exact: true }).fill('左框')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  const groups = page.getByTestId('object-group')
  await expect(groups).toHaveCount(1)
  await page.getByTitle('隐藏选中对象', { exact: true }).click()
  await page.getByTestId('object-search').fill('nothing')
  await groups.first().getByRole('button').first().click()
  expect((await store(page)).selectedIds).toEqual(['first', 'second'])
  await expect(page.getByTestId('object-search')).toHaveValue('')
  await expect(page.getByTestId('object-row').filter({ hasText: 'P-first' })).not.toHaveClass(/is-hidden/)
  await groups.first().getByTitle('重命名组', { exact: true }).click()
  await page.getByRole('textbox', { name: '组名称', exact: true }).fill('侧框')
  await page.getByRole('button', { name: '确定', exact: true }).click()
  await expect(groups.first()).toContainText('侧框')
  // Move focus out of the name form before exercising editor shortcuts.
  await page.getByTestId('sidebar-tab-objects').click()
  await page.keyboard.press('Control+c')
  await page.keyboard.press('Control+v')
  await expect(groups).toHaveCount(2)
  const metadata = await page.evaluate(() => (window as any).__aluframe.store.getState().groups)
  expect(metadata[1].name).toBe('侧框')
  expect(metadata[1].id).not.toBe(metadata[0].id)
  expect(metadata[1].memberIds.every((id: string) => !metadata[0].memberIds.includes(id))).toBe(true)
  await page.keyboard.press('Control+z')
  await expect(groups).toHaveCount(1)
  await groups.first().getByTitle('解散组，保留零件', { exact: true }).click()
  await expect(groups).toHaveCount(0)
  expect((await store(page)).profiles).toHaveLength(2)
  await page.keyboard.press('Control+z')
  await expect(groups).toHaveCount(1)
  await page.evaluate(() => (window as any).__aluframe.tool.setState({ viewMode: true }))
  await expect(groups.first().getByTitle('重命名组', { exact: true })).toBeDisabled()
  await expect(groups.first().getByTitle('解散组，保留零件', { exact: true })).toBeDisabled()
})
